// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/:role": {
    params: {
      "role": string;
    };
  };
  "/:role/*": {
    params: {
      "role": string;
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/:role" | "/:role/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/$role.tsx": {
    id: "role-root";
    page: "/:role";
  } | {
    id: "role-splat";
    page: "/:role/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "role-root": typeof import("./app/routes/$role.tsx");
  "role-splat": typeof import("./app/routes/$role.tsx");
};